site:
    title: "Bigzhu's den"
    subtitle: "学习生活以及吐糟昆明的 IT"
    limit: 40
    theme: theme
    lang: zh
    url: "http://bigzhu.lorstone.com"
    comment: bigzhu
    logo: "-/images/logo.png"
    # link: "{category}/{year}/{month}/{day}/{title}.html"
    # root: "/blog"

authors:
    me:
        name: "bigzhu"
        intro: "Everything is learnable"
        avatar: "-/images/tou.jpg"

build:
    # output: "public"
    port: 8000
    # Copied files to public folder when build
    copy:
        - "source/images"
    # Excuted command when use 'ink publish'
    publish: |
        git add . -A
        git commit -m "update"
        git push origin
